# Generated by Django 3.2.9 on 2022-01-05 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220105_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular blog post.', primary_key=True, serialize=False),
        ),
    ]
